apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-hpa
  namespace: hello-world
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: hello-world-deployment
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  targetCPUUtilizationPercentage: 50  # Target CPU utilization percentage to scale
